#!/usr/bin/env tsx

import { readdirSync, readFileSync, statSync, writeFileSync } from 'fs';
import { basename, dirname, extname, join, relative } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');

// Paths
const assetsDir = join(rootDir, 'src/lib/assets/images');
const outputFile = join(rootDir, 'src/lib/assets/image-assets.ts');

interface ImageFile {
	path: string;
	relativePath: string;
	key: string;
}

/**
 * Recursively find all image files
 */
function findImageFiles(dir: string, baseDir: string = dir): ImageFile[] {
	const files: ImageFile[] = [];
	const items = readdirSync(dir);

	for (const item of items) {
		const fullPath = join(dir, item);
		const stat = statSync(fullPath);

		if (stat.isDirectory()) {
			files.push(...findImageFiles(fullPath, baseDir));
		} else if (stat.isFile()) {
			const ext = extname(item).toLowerCase();
			if (['.jpg', '.jpeg', '.png', '.webp'].includes(ext)) {
				// Use path.relative for cross-platform compatibility
				const relativePath = relative(baseDir, fullPath).replace(/\\/g, '/');
				files.push({
					path: fullPath,
					relativePath,
					key: generateKey(relativePath)
				});
			}
		}
	}

	return files;
}

/**
 * Generate a clean key from file path
 */
function generateKey(relativePath: string): string {
	// Convert path like "projects/cover-crypto-trading-bot.jpg" to "cryptoTradingBot"
	// or "articles/il-mio-nuovo-laboratorio/featured.jpg" to "ilMioNuovoLaboratorioFeatured"

	const pathParts = relativePath.split('/');
	const filename = basename(
		pathParts[pathParts.length - 1],
		extname(pathParts[pathParts.length - 1])
	);

	let key = '';

	if (pathParts[0] === 'projects') {
		// For projects: remove "cover-" prefix if present
		key = filename.replace(/^cover-/, '');
	} else if (pathParts[0] === 'articles') {
		// For articles: combine folder name + filename
		const articleSlug = pathParts[1];
		key = articleSlug + '-' + filename;
	}

	// Convert kebab-case to camelCase
	return key
		.split('-')
		.map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
		.join('');
}

/**
 * Convert image to base64 data URI
 */
function imageToBase64(filePath: string): string {
	const buffer = readFileSync(filePath);
	const ext = extname(filePath).toLowerCase();

	let mimeType: string;
	switch (ext) {
		case '.jpg':
		case '.jpeg':
			mimeType = 'image/jpeg';
			break;
		case '.png':
			mimeType = 'image/png';
			break;
		case '.webp':
			mimeType = 'image/webp';
			break;
		default:
			throw new Error(`Unsupported image type: ${ext}`);
	}

	const base64 = buffer.toString('base64');
	return `data:${mimeType};base64,${base64}`;
}

/**
 * Main function
 */
function main(): void {
	console.log('🔍 Scanning for images...');
	const imageFiles = findImageFiles(assetsDir);

	console.log(`📷 Found ${imageFiles.length} images`);

	const assets: Record<string, string> = {};
	let totalSize = 0;

	for (const file of imageFiles) {
		console.log(`📝 Processing: ${file.relativePath} -> ${file.key}`);

		try {
			const dataUri = imageToBase64(file.path);
			assets[file.key] = dataUri;

			// Calculate size for reporting
			const sizeKB = Math.round((dataUri.length * 0.75) / 1024); // rough base64 to bytes conversion
			totalSize += sizeKB;

			console.log(`   ✅ ${sizeKB}KB`);
		} catch (error) {
			console.error(`   ❌ Error processing ${file.relativePath}:`, (error as Error).message);
		}
	}

	// Generate TypeScript file
	const tsContent = `// Auto-generated image assets for OG image generation
// This file is generated by scripts/generate-image-assets.js
// Do not edit manually

export interface ImageAssets {
  [key: string]: string;
}

export const imageAssets: ImageAssets = {
${Object.entries(assets)
	.map(([key, dataUri]) => `  '${key}': '${dataUri}',`)
	.join('\n')}
};

// Helper function to get image by key
export function getImageAsset(key: string): string | null {
  return imageAssets[key] || null;
}

// Available image keys
export const availableImages = ${JSON.stringify(Object.keys(assets), null, 2)};

// Stats
export const imageStats = {
  totalImages: ${Object.keys(assets).length},
  totalSizeKB: ${totalSize},
  generatedAt: '${new Date().toISOString()}'
};
`;

	writeFileSync(outputFile, tsContent);

	console.log('');
	console.log('✨ Image assets generated successfully!');
	console.log(`📊 Total: ${Object.keys(assets).length} images, ~${totalSize}KB`);
	console.log(`📄 Output: ${outputFile}`);
	console.log('');
	console.log('Available keys:');
	Object.keys(assets).forEach((key) => console.log(`  - ${key}`));
}

main();
