// Auto-generated image assets for OG image generation
// This file is generated by scripts/generate-image-assets.ts
// Do not edit manually
//
// All images are optimized and converted to JPEG format for consistency
// Using Sharp with quality 80%, max size 720x408px

export interface ImageAssets {
  [key: string]: string;
}

export const imageAssets: ImageAssets = {

};

// Helper function to get image by key
export function getImageAsset(key: string): string | null {
  return imageAssets[key] || null;
}

// Available image keys
export const availableImages = [];

// Stats
export const imageStats = {
  totalImages: 0,
  totalSizeKB: 0,
  optimizationConfig: {
  "quality": 80,
  "maxWidth": 720,
  "maxHeight": 408,
  "progressive": true,
  "mozjpeg": true
},
  generatedAt: '2026-05-31T14:32:09.648Z'
};
